### ISSUE TITLE
Two pictures are invalid

### ISSUE THREAD

**Issue by tianheg** [reuixiy/io-oi.me#125]
Here https://io-oi.me/tech/hexo-next-optimization/#%E8%B0%B7%E6%AD%8C%E5%88%86%E6%9E%90

**Comment by reuixiy** [comment]
It's valid on my machine. Might be a network problem. Try `ctrl` + `shift` + `r` after setup network proxy.

**Comment by tianheg** [comment]
It works!

> It's valid on my machine. Might be a network problem. Try `ctrl` + `shift` + `r` after setup network proxy.
