### ISSUE TITLE
Install app

### ISSUE THREAD

**Issue by mrfoxie** [reuixiy/io-oi.me#154]
![xvx2Glejwx](https://user-images.githubusercontent.com/25217451/126736217-4b4bcc76-6ecf-4830-b6e8-571d17e2c45e.png)
how did you add this option to your site?

**Comment by tianheg** [comment]
https://io-oi.me/tech/a-simple-service-worker/

**Comment by mrfoxie** [comment]
I tried but it's not working

> https://io-oi.me/tech/a-simple-service-worker/

**Comment by tianheg** [comment]
@mrfoxie My Deploy: https://github.com/tianheg/blog/commit/7a941d32735cd8c0eee79435d6d705a7a1b92e1a

Hope this will help you

**Comment by mrfoxie** [comment]
I tried it but no change [d703b6b](https://github.com/mrfoxie/mistrysiddh/commit/aa3c7711aeb28a7bff9b1156d6c5f0cff08bd7d0)

**Comment by reuixiy** [comment]
@mrfoxie That's PWA install prompt from browser. Check https://web.dev/progressive-web-apps/ especially https://web.dev/codelab-make-installable/
