### ISSUE TITLE
博客内容是issues自动生成的吗？

### ISSUE THREAD

**Issue by tuduweb** [reuixiy/io-oi.me#155]
请问一下博客内容是issues的内容自动生成的吗？还是只是写想法，再通过markdown来完成写作呢。

没想清楚这个逻辑。能简单介绍一下吗。

**Comment by tianheg** [comment]
@reuixiy 当然是后一种啊

**Comment by reuixiy** [comment]
@tuduweb 不是的哦，我的流程是在 Issue 笔记所看或记录突发奇想，持续性地记录和关联。博客的文章，有时是 Issue 里记录的然后写成 Markdown 然后在文章发布的时候关闭 Issue，有时是直接想写这篇文章，不打草稿。Issue 现在可以理解为我的笔记本和草稿本吧。
