### ISSUE TITLE
Hello, Arch Linux! 纠错

### ISSUE THREAD

**Issue by tianheg** [reuixiy/io-oi.me#158]
3.3.7 安装输入法

> GNOME 设置界面 > Region & Language > Input Sources，删除 English。

这句中，Region & Language 应改为 Keyboard，因为并未在 Region & Language 中找到对应设置。

以上更改，并不保证正确。

因为这篇文章写于 2018 年，可能那时的 GNOME 设置就是如此。

**Comment by reuixiy** [comment]
是的 哈哈 GNOME 就喜欢这样变来变去

PR welcome

**Comment by tianheg** [comment]
好的，待我明天装好 Arch。今天装好了，因为一个问题，怀疑是硬盘的问题，所以又重装了。但眼睛特别疲劳需要休息。

问题：

1. lsusb not found
2. service not found

硬盘：

2块硬盘，1块固态，120g，1块机械，930g。

第一次安装时，efi分区和/目录放在固态，整个机械作为/home，内存大约23g

第二次，机械没用，efi分区和/目录放在固态

当我安装到检查蓝牙芯片时，lsusb 仍然 not found，service 也是

这时，我明白不是硬盘的问题。
