### ISSUE TITLE
你好，我想问你关于「框架」的看法？

### ISSUE THREAD

**Issue by tianheg** [reuixiy/io-oi.me#181]
问题定义：

「框架」指的是，对于某一技术/领域的宏观把握，这一技术在其外在系统中所占据的作用。亦即，整体性思维/系统性思维。

背景：

今天，讲授嵌入式课程的老师，从冯·诺依曼结构以及后来的哈佛结构，讲到人的生物结构，进而推及到学习过程中掌握框架的重要性。现在的我学习前端的过程就忽视了把握整体的脉络，只在局部做文章。我耗费了很多精力，到头来却发现收获甚少。

我对你的关注很多，我知道你写作、阅读，也知道你在从事编程工作、思考人生哲学。每次看你写 issue 是一种享受，也很好奇。为什么你可以涉猎这么多领域的知识？比如，哲学、计算机科学，以及其他现代科技。看到你涉猎甚广，我却只关注于某一小块，便觉得自己还需要做些什么，却不知道从何做起。

介绍一下自己：我是 22 届应届生，从去年疫情刚开始接触编程，也和你一样，决定以前端工程师的身份进入社会。我习惯于思考问题，虽然很多问题都和实际没有太大关系。试图寻找有一种方法论，妄想解决一切问题，后来发现不可能。但是在寻找方法论的过程中，我发现虽然不能一劳永逸，但是可以先以现有条件，构建一个最小可执行的方法论，之后可以不断迭代。

问题：

1. 你对于前端技术的学习过程，有建立一个框架吗？它是怎样形成的？
2. 你是基于怎样的想法/思考，选择接触 issues 中的各个主题的？（换句话说，你在 issues 中记录的内容，是你有意识地成体系地去了解的呢？还是你碰巧遇到了，恰好感兴趣，就记录下来的？）
3. 我给自己构建的未来要学习的两个部分（了解自己、认识世界），前者可以对应社会科学（哲学、心理学等），后者可以对应自然科学（计算机科学、生物学等），而这两对之间又有着联系。我曾经在你的博客《毕业烦心事》中读到你接触哲学、计算机科学的经过。我的问题是，你现在对于哲学、计算机科学的认识到了什么程度，你认为你从其中收获了哪些呢？

PS：

如果你对我哪一部分的阐述有不清楚的，请一定指出，我会改正。以上就是我想表达的大概意思。

**Comment by tianheg** [comment]
和室友讨论「学习某样事物在最开始的时候具有一个框架是否重要？」：

室友认为，一开始的框架是别人提供的，不经过自己的思考无法成为自己的理解；而通过学习事物的细节，最终能够得到自己的轮廓，是属于自己的内容。

**Comment by reuixiy** [comment]
你指的框架是一种心智模型类似的东西，可能两种方式形成：

1. 直觉演绎
2. 经验归纳

两者的联系关系是多样的，比如先后、主次。

问题一：有，自己的理解加上新知识的学习堆积而来的
问题二：是看到相关内容的自己的理解，或者突发奇想，但我之所以会选择这些「相关内容」可能与我的兴趣有关
问题三：外行人程度，收获了知识和理智的愉悦

学习者担忧的无非是深度和广度，不过单纯的学习本身只是一种好奇心罢了，好奇心不会让人担忧，让学习者产生担忧的原因可能是自己想从中获得其它的「好处」，所以担忧，比如担忧是否能超越他人，担忧是否能用来挣钱。但是学习本身只是一种好奇心，至于学习最终的「框架」与否，取决于自己的理解和追求。本着好奇心，多学而识，循着一以贯之，自然而然会有自己的心智模型。对 Web 前端来说，只是一个工程性的东西，不断地接触新的知识，能看到现有实践中的不足，并去改进，自然而然会有自己的「框架」。个人来说，方法或工具，除了自己的直觉演绎，受益最多的还是写作吧，https://io-oi.me/tech/on-three-questions-about-blogging/

**Comment by tianheg** [comment]
> 好奇心不会让人担忧，让学习者产生担忧的原因可能是自己想从中获得其它的「好处」，所以担忧，比如担忧是否能超越他人，担忧是否能用来挣钱。

谢谢你。你的解释，引起我的思考。

**Comment by tianheg** [comment]
最近读到一篇 @geekplux 写的《[建立索引式的学习方法](https://geekplux.com/posts/learning-by-index)》，和我想表达的框架有相似之意。

在学习新的技能（软件、工具）时，知晓每一处知识点（功能）的用处是什么，它能解决什么问题。
