### ISSUE TITLE
标题如何居中？

### ISSUE THREAD

**Issue by yangliuly1** [reuixiy/io-oi.me#220]
![image](https://user-images.githubusercontent.com/43691492/155985687-93e7192a-5401-481d-ab0c-6f8aa1b36614.png)

**Comment by tianheg** [comment]
标题默认居中，你进行了哪些修改让标题不居中了

**Comment by yangliuly1** [comment]
> 标题默认居中，你进行了哪些修改让标题不居中了

我仅仅是修改了一下文章 二级标题都不能居中

**Comment by tianheg** [comment]
能不能把你的仓库上传到GitHub，不提供代码无法复现

**Comment by reuixiy** [comment]
@yangliuly1 这是因为我为关于页面的标题特殊定制了一下，见

https://github.com/reuixiy/io-oi.me/blob/0cfba4b3173a4fb344d1f9a7d289c957ec8d77e5/content/zh/about/_index.md?plain=1#L8

https://github.com/reuixiy/io-oi.me/blob/0cfba4b3173a4fb344d1f9a7d289c957ec8d77e5/assets/scss/custom/_custom.scss#L90-L99

**Comment by yangliuly1** [comment]
Thanks.
