### ISSUE TITLE
我的about页的视频播放卡

### ISSUE THREAD

**Issue by Rurouni-z** [reuixiy/io-oi.me#232]
我目前就单单用的是免费的pinata，这个有影响吗
我看博主的视频加载非常快，而且是100mb大小，我这个才40mb大小的视频
[我的博客](https://keepjolly.com/about/)、[视频地址](https://gateway.pinata.cloud/ipfs/QmTz7jzWdGrTVKT7YwNwX9cEgfg4smNFHVxnaFDR82BrXt)

还有点不好意思，基本都用的是博主的风格😂

**Comment by tianheg** [comment]
你是不是开了广告屏蔽插件

**Comment by Rurouni-z** [comment]
> > 你是不是开了广告屏蔽插件
> 
> 还有这种说法，我确实开了adblock😂，那为什么我访问博主的不会卡顿，我清缓存也不会卡顿
> 
> 刚好在看你的博客🤣

好像确实不卡了，这也太神奇了

**Comment by tianheg** [comment]
我用了 uBlock Origin，它直接把这个视频给屏蔽了

**Comment by Rurouni-z** [comment]
> 

更新，我用火狐看还是放到一半还会卡顿，估计不是插件的原因

**Comment by Rurouni-z** [comment]
> 我用了 uBlock Origin，它直接把这个视频给屏蔽了

更新，我用火狐看还是放到一半还会卡顿，估计不是插件的原因

**Comment by tianheg** [comment]
我完整地播放完了你的视频，没有卡顿，在 Firefox Developer Edition v114.0b5 (Arch Linux)

**Comment by Rurouni-z** [comment]
> 我完整地播放完了你的视频，没有卡顿，在 Firefox Developer Edition v114.0b5 (Arch Linux)
> 
> 更新：
> 
> 有看过 Devtools Console/Network 里有什么报错/异常吗

有报错，但是还没复现出来，另外可以试试ctrl + f5 清空缓存吗，那或许是我网络问题，我现在开着clash

**Comment by tianheg** [comment]
在无痕模式下试试，如果还看不到播放中断的时刻，可能就是你的网络（代理）问题

**Comment by Rurouni-z** [comment]
> 在无痕模式下试试，如果还看不到播放中断的时刻，可能就是你的网络（代理）问题

是的，我的代理速度不够，以前看了博主的文章估计缓存下来了，现在用无痕模式看博主的文章也是卡死

**Comment by Rurouni-z** [comment]
> 既然公开展示开源出来了，就不怕你用 :doge:
> 
> 我前段时间也发现 Pinata 的链接会被 Block，一直还没处理，加载速度的话，和网络节点可能会有比较大关系，然后就是你要让足够多的 IPFS 节点有你的视频数据，我当时好像注册了好几个 Pinata 账号然后把我博客的视频都 Pin 了，还去各种公开的 IPFS Gateway 访问以获得更多节点缓存 😂
> 
> 视频问题的话，我已经打算把博客的视频都迁移到 YouTube 了，见 #71（转眼三年前...）

hh，好的。那个issue我也看到了，抓紧干吧2333
