### ISSUE TITLE
我有一个小疑问：

### ISSUE THREAD

**Issue by dawnow** [reuixiy/io-oi.me#31]
开发者你好，我在写自己博客的时候又遇到了一个问题，就是图片下面的说明文字，就比如说下面这张图片，我已经在[ ]里面写了内容，不知道为啥不显示？我平时用的编辑器是Typora，也无法实现这项功能，不知道是什么原因呢？
![Google](https://dawnblog-1300625500.cos.ap-guangzhou.myqcloud.com/images/snap.jpg)
请大佬解答？

**Comment by reuixiy** [comment]
```md
![alt](url "title")
```

说明文字是取的 `title` 的值。

**Comment by reuixiy** [comment]
这项功能是主题自己实现的，所以你用的编辑器的确无法显示相应的内容。

此外，注意到你博客下图中的链接乱码，最新版的主题已经解决这个问题，更新主题即可解决～

![2019-12-24-20-51-20](https://user-images.githubusercontent.com/28993043/71413906-52d39c00-268f-11ea-934c-701f4887dc4a.png)

**Comment by dawnow** [comment]
> 这项功能是主题自己实现的，所以你用的编辑器的确无法显示相应的内容。
> 
> 此外，注意到你博客下图中的链接乱码，最新版的主题已经解决这个问题，更新主题即可解决～
> 
> ![2019-12-24-20-51-20](https://user-images.githubusercontent.com/28993043/71413906-52d39c00-268f-11ea-934c-701f4887dc4a.png)

感谢！👍
