### ISSUE TITLE
视频出现问题

### ISSUE THREAD

**Issue by dawnow** [reuixiy/io-oi.me#35]
更新到最新版本后，本地预览或者部署后视频都无法显示。但在typora里面可以正常显示和观看。
视频嵌入使用的是下面的HTML代码：
`<video id="video" controls="" preload="none" poster="">
      <source id="mp4" src="">
      </video>`
以前的博客中以此方法插入的视频也都无法显示了
博客地址：https://sailordawner.top/

**Comment by reuixiy** [comment]
你好！因为新的 Markdown 渲染器 Goldmark 默认会剔除 HTML 代码，所以你需要更新 `config.toml` 中的配置，请参见[`config.toml` 的改动历史](https://github.com/reuixiy/hugo-theme-meme/commits/master/config-examples/zh-cn/config.toml)自行更新该文件。

> 需要注意的是，MemE 的示例配置是会随着 MemE 的更新而更新的，而有一些变动可能会让旧的示例配置无法工作。因此，在你更新主题前，请先查看示例配置的改动历史，并将改动手动同步到你的 config.toml 文件中。
>
> — *https://io-oi.me/tech/documentation-of-hugo-theme-meme/#配置*

另，MemE 主题使用的问题，请移步[主题的 Issues 区](https://github.com/reuixiy/hugo-theme-meme/issues)反馈。
