### ISSUE TITLE
question about ur blog

### ISSUE THREAD

**Issue by Xuezenghuigithub** [reuixiy/io-oi.me#4]
我之前也是跟着你博客的[教程](https://io-oi.me/tech/hexo-next-optimization/)使用Hexo搭建了[我的博客](https://xuezenghui.com)，如你所见，我承认其确实太糟糕了——访问速度极其慢，这也是我又follow你又开始捣鼓Hugo的原因。我疑惑的地方在于[io-oi.me](https://io-oi.me/)是如何将**Hugo**源码托管于Github而在**Netlify**上部署且访问速度还如此迅速的...

**Comment by reuixiy** [comment]
@Xuezenghuigithub 你好！

这就是持续集成，源码通过 Git 进行版本控制并放在 GitHub，之后配置 Netlify 使一但 GitHub 上的源码有改动，Netlify 的服务器就自动拉取最新版的源码构建并部署。

如果你疑惑的是构建，其实这和你在本地运行 Hugo 没有区别，只不过这里是直接通过 Netlify 的服务器在云端运行；如果你疑惑的是部署，其实这和你本地 Hexo 将生成的 HTML 等文件部署到 GitHub 上没有什么区别，只不过这里是 Netlify 的服务器自动将云端生成的 `public` 文件夹部署到 Netlify 的服务器上；如果你疑惑的是如何去配置，可以查看我写的 [IPFS](https://io-oi.me/tech/host-your-blog-on-ipfs/) 的那篇文章，只不过你可以将 IPFS 相关的步骤全部省略。至于速度快，静态站点本来就快，再加上我的博客是极简的，MemE 主题也是极简的。当然，这可能也与我使用了 Service Worker 来预缓存有关，见[利用 Workbox 实现博客的 PWA](https://io-oi.me/tech/pwa-via-workbox/)。

最后，MemE 主题有了中文的 README 和 `config.toml` 配置示例，建议立即查看。至于 MemE 主题的完整文档和我说的那篇通俗易懂的教程可能暂时写不出来了，目前只写了一篇残缺的 [Hugo 主题 MemE 文档](https://io-oi.me/tech/documentation-of-hugo-theme-meme/)。

**Comment by Xuezenghuigithub** [comment]
哈哈哈，感谢你的回复和所有精彩的文章，我周五周六已经按照你中文的`config.toml`重新配置了MemE主题——已经足够通俗易懂了，也仔细研读IPFS部署的文章，但是暂时还没尝试，总之，感谢分享😉

**Comment by reuixiy** [comment]
好的 :smile_cat:
