### ISSUE TITLE
博客首字下沉效果实现

### ISSUE THREAD

**Issue by linwhitehat** [reuixiy/io-oi.me#43]
首字下沉效果是更改文字css样式吗？请问在哪个配置文件做修改？

**Comment by reuixiy** [comment]
你好，

MemE 主题自带的，可以在配置文件中全局开启，或者在文章上方的 Front Matter 中添加 `dropCap: true` 手动开启。见：https://github.com/reuixiy/hugo-theme-meme/blob/76018fb93fb4bddbd4a647f838ad50a51337087a/config-examples/zh-cn/config.toml#L908-L914
