### ISSUE TITLE
部署到ipfs发生错误

### ISSUE THREAD

**Issue by Xuezenghuigithub** [reuixiy/io-oi.me#5]
你好，我在部署到ipfs后出现了问题，说是Cloudflare的Origin DNS错误——[xuezenghui.com](https://www.xuezenghui.com/)，我只配置了一条CNAME但是Cloudflare提示应用了CNAME合并🤪请问一休儿有什么解决办法吗？我太难了
![error.png](https://img-blog.csdnimg.cn/2019111114030323.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L1h1ZV96ZW5naHVp,size_16,color_FFFFFF,t_70)

**Comment by Xuezenghuigithub** [comment]
还有一点比较疑惑：[文章](https://io-oi.me/tech/host-your-blog-on-ipfs/)中没有看到Netlify中域名的配置或在Cloudflare中配置Netlify的域名解析相关说明，请问是省略了还是只需要按照文章中的步骤就可完整地实现ipfs部署及Netlify持续集成？

**Comment by Xuezenghuigithub** [comment]
这是我执行`npm run ipfs-deploy`后的信息：
```
> xuezenghui.com@1.0.0 ipfs-deploy /Users/zander/xuezenghui.com
> ./node_modules/ipfs-deploy/bin/ipfs-deploy.js -p infura public -p pinata public -u pinata -d cloudflare -C -O

✔ 🚚  Directory public weighs 1.1 MiB.
✔ 📌  Added and pinned to Pinata with hash:
ℹ 🔗  QmU67ufB4iZUgZE1vs9eAjorQ13EeedP3pUERi4Kq22ogQ (​https://gateway.pinata.cloud/ipfs/QmU67ufB4iZUgZE1vs9eAjorQ13EeedP3pUERi4Kq22ogQ/​)
✖ 💔  Pinning to Infura didn't work.

  ┌─────────────────────────────────────────────────────────────────────────────────────────┐
  │                                                                                         │
  │ Error: connect ETIMEDOUT 69.63.184.142:5001                                             │
  │                                                                                         │
  └─────────────────────────────────────────────────────────────────────────────────────────┘
ℹ 📡  Beaming new hash to DNS provider Cloudflare…
(node:76474) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
✔ 🙌  SUCCESS!
ℹ 🔄  Updated DNS TXT _dnslink.xuezenghui.com to:
ℹ 🔗  dnslink=/ipfs/QmU67ufB4iZUgZE1vs9eAjorQ13EeedP3pUERi4Kq22ogQ
```

**Comment by reuixiy** [comment]
@Xuezenghuigithub

1. CNAME 的提示是正常的
2. 删除你自己添加的多余的 `dnslink`
3. 域名的 DNS 已经移交给 Cloudflare 管理，没有 Netlify 的事了，Netlify 现在的作用只是一台为我们生成 `public` 文件夹并将之上传到 Pinata 的服务器和更新 Cloudflare 上的 DNS 记录的云服务器
4. 本地测试是成功的，其中的一个报错是正常的，可能是 Infura 已被墙了或它的服务器宕机了
5. 请自己多尝试，一一排除

**Comment by Xuezenghuigithub** [comment]
@reuixiy 谢谢你，问题有两个：
1. 原来的域名解析中确有一条多余的`dnslink`
2. 发布到Netlify后是需要在Domain Setting中将域名更改为`example.netlify.com`格式，而非Netlify产生的默认域名，否则[文章](https://io-oi.me/tech/host-your-blog-on-ipfs/)中提到的`netlify.toml`文件是不生效的，这点如果注意不到可能对小白有些不友好，建议你能在文章中做一下提醒。
---
感谢分享😊

**Comment by reuixiy** [comment]
？？这个 :joy_cat: 算了吧

**Comment by reuixiy** [comment]
done
