### ISSUE TITLE
iPhone博客显示问题

### ISSUE THREAD

**Issue by CurtainTears** [reuixiy/io-oi.me#52]
会有一些文字上面有一个框，请看截图
![image](https://user-images.githubusercontent.com/16211800/74507545-b19eee80-4f37-11ea-9f14-b4497e571086.png)

**Comment by reuixiy** [comment]
感觉应该是 [glyph-correction](https://github.com/reuixiy/hugo-theme-meme/tree/master/static/fonts) 这个自定义的字体子集的原因，不过现在我身边没设备，没法调试。

**Comment by reuixiy** [comment]
我当时用 FontForge 修改生成的，但这个工具好像有点问题，会多生成字符。刚刚找了几个 GitHub 上的工具试了试，解决了多生成字符的问题，见 https://github.com/reuixiy/hugo-theme-meme/commit/ffc6aa7627c5e30980e5e02cd055a6ad969cb589

但你反馈的这个问题有没有解决我就不知道了，还需等待你的测试结果。

**Comment by CurtainTears** [comment]
更新了主题之后，问题并没有得到解决，你的博客也还是原样，我发现在一些比如列表，角标的字符之后就会出现这种情况。并且不同的iPhone上这个框所在的字符是不同的，但是全都是在数字后的第一个中文或者角标后的第一个中文。

**Comment by CurtainTears** [comment]
不确定是iPhone的问题还是主题的问题。
复现方法，写一个超过10行的列表，用iPhone访问博客。

**Comment by reuixiy** [comment]
是 Safari 浏览器的问题，我搜到一个类似的问题，在 <https://github.com/FortAwesome/Font-Awesome/issues/7770>，但看起来好像也没有一个有效的 Workaround。不过你可以测试一下 [Issue](https://github.com/FortAwesome/Font-Awesome/issues/7861) 中提到的 CSS 代码 `text-rendering: optimizeLegibility;`。

当然，把主题的「中文标点符号字形纠正」功能关掉，就不会加载 font-correction 这个字体，也就不会有这个问题。

**Comment by reuixiy** [comment]
emmm 不小心关闭了 你可以再测试下 要是还不行那我也没招了:joy:

**Comment by CurtainTears** [comment]
应该和中文标点纠正没什么关系，打开关闭是一样的效果。我怀疑可能是Safari对li标签的支持度的问题。

**Comment by CurtainTears** [comment]
经过一些电脑上的Safari浏览器的调试，我发现有一些字在某一个<li>签中的第一个就会出现框，有一些是不会的。   可能是safari对中文渲染出现的随机bug。应该是解决不了了。 emmmmmm

**Comment by reuixiy** [comment]
OK

**Comment by CurtainTears** [comment]
成功定位到问题，网络字体思源宋体的问题。取消网络字体后，Safari渲染不再有问题

**Comment by reuixiy** [comment]
好的:joy:

**Comment by Jecvay** [comment]
我也碰到这个问题，有没有办法保持网络字体的基础上，解决
