### ISSUE TITLE
博客代码块路径显示问题

### ISSUE THREAD

**Issue by linwhitehat** [reuixiy/io-oi.me#55]
你好，请问博客中加入代码块能设置自动显示文件路径吗？还是只能在代码块中自己写入？我目前只知道代码块能够写入语言进行代码高亮，还有其他参数可以设置吗？

**Comment by reuixiy** [comment]
根据相关 Markdown 细则，<code>```</code> 后面的文字叫 [info string](https://spec.commonmark.org/0.29/#info-string)，而细则中只提了一个参数，就是第一个通常是代码的语言名（The first word of the info string is typically used to specify the language of the code sample）。所以它的实现——即你所说的参数——是取决于 Markdown 渲染器的。

你问的应该是 Hexo 吧？看了下，Hexo 的默认 Markdown 渲染器 [hexo-renderer-marked](https://github.com/hexojs/hexo-renderer-marked) 用的 [marked](https://github.com/markedjs/marked) 中并没有我在[文中提到的参考](https://io-oi.me/tech/hexo-next-optimization/#主题自带样式-代码块高亮)的相关代码。Hexo 应该是自己添加的，见 [backtick_code_block.js](https://github.com/hexojs/hexo/blob/master/lib/plugins/filter/before_post_render/backtick_code_block.js) 和 [highlight.js](https://github.com/hexojs/hexo-util/blob/master/lib/highlight.js)，不过这两个文件里也没相关注释说明，我也没细看，但我猜支持的参数应该是与 Hexo 的标签插件 [Code Block](https://hexo.io/docs/tag-plugins#Code-Block) 相同的。

Hugo 的话，见 https://gohugo.io/content-management/syntax-highlighting/#highlighting-in-code-fences
