### ISSUE TITLE
新版顶栏设计好漂亮！

### ISSUE THREAD

**Issue by he-sb** [reuixiy/io-oi.me#58]
但是有个小小的 bug ，这个背景颜色是半透明的，文章向下滚动之后正文会和顶栏内容重叠，看起来怪怪的 🌚 

![图片](https://user-images.githubusercontent.com/26474615/75904043-78de9f00-5e7d-11ea-9bf5-baf5a5c71a61.png)

**Comment by reuixiy** [comment]
哈哈，谢谢！

这个是浏览器的兼容性问题，可能你使用的是版本较低的浏览器或 Firefox，以下是 Chrome 下的效果：

![2020-03-05-09-36-54](https://user-images.githubusercontent.com/28993043/75939555-799b2380-5ec5-11ea-8133-94b9d439d2d8.png)

使用了一个较新的 CSS 属性`backdrop-filter`，其支持情况见：https://caniuse.com/#feat=css-backdrop-filter

不过这样对不支持此属性的浏览器的确有点问题，正在想解决方法……

**Comment by he-sb** [comment]
喔毛玻璃效果很赞，我的确是firefox 73.0.1 🙈
