### ISSUE TITLE
主题样式定制不生效，不知是我没搞对还是bug

### ISSUE THREAD

**Issue by tttlkkkl** [reuixiy/io-oi.me#79]
文章下的分类链接由于我菜单名较长导致在手机上换行显示了，只是一字之差我想调整一下，但是在`_custom.scss`中添加样式没有生效，麻烦帮指正一下，谢谢。
![image](https://user-images.githubusercontent.com/8353103/81365123-e925cd00-9119-11ea-8341-6716fd604a34.png)
![image](https://user-images.githubusercontent.com/8353103/81365372-7f59f300-911a-11ea-8a54-ab376bce263d.png)

**Comment by reuixiy** [comment]
路径不正确，应该是 assets/**scss**/custom/_custom.scss，少了个 `scss`。

**Comment by tttlkkkl** [comment]
@reuixiy 果然是少了scss这个路径，希望更新一下https://io-oi.me/tech/documentation-of-hugo-theme-meme/这篇文档中的内容，我就是看着这里改的。再次感谢。你的主题很棒！

**Comment by reuixiy** [comment]
没事。原来是我的失误，已纠正，感谢反馈 :)
