### ISSUE TITLE
blog 不打算开评论了吗

### ISSUE THREAD

**Issue by Jecvay** [reuixiy/io-oi.me#81]
顺便问下 一般在哪里写作 vscode 还是别的什么

切换设备都 git pull 一遍吗

**Comment by Jecvay** [comment]
感觉 theme 特别棒. 可以拿去用吗

**Comment by reuixiy** [comment]
评论不打算了。

写作看个人喜好，Markdown 文本文档，用自己喜欢的编辑器码字就是。

是的，最好 pull 一下，以防版本冲突。当然，如果你能每次清晰地记得各设备上的各版本情况……

谢谢，主题是开源的，可以的。
