### ISSUE TITLE
想问下博主的图片是怎样添加的？

### ISSUE THREAD

**Issue by driftingdream** [reuixiy/io-oi.me#83]
我使用的是Hugo搭建的博客，采用了博主写的Meme主题。
Hugo对图片的添加我认为不是很友好，看了博主的markdown代码，发现都是用绝对路径添加的，我一开始也是这样实现的，但发现很麻烦。具体流程有以下几步：将图片保存在`/static/image/`下 -> 检查图片名称是否与其他重复 -> 文章填入图片路径`/image/***`。
这种写文章的流程是割裂的，并且在编辑软件上无法正常显示图片。我想要的功能就是可以文章与图片在`/posts/文章名称.md`同一个文件夹中，并且文章markdown中使用相对路径。这个方式可以在Hugo的`uglyUrls`中可以实现，但是标签、分类、关于的页面就无法正常打开了。[理想的实现方式](https://github.com/Himself65/himself65.github.io/tree/dev/content/blog)
请问你有什么建议吗？

**Comment by driftingdream** [comment]
魔改了下主题的配置文件，请问这样会有什么问题吗
<img width="310" alt="image" src="https://user-images.githubusercontent.com/16973422/87813960-7c574d80-c895-11ea-9699-9d7b5f7e7ec0.png">

**Comment by reuixiy** [comment]
> 我想要的功能就是可以文章与图片在 `/posts/文章名称.md` 同一个文件夹中

你说的应该是 `/posts/文章名称/index.md`，然后图片是 `/posts/文章名称/image.png`，如此文章和图片就在一个文件夹下。

Hugo 应该是支持的，按你给的链接中的仓库，组织方式是：

```
content/posts/test/
.
├── image.png
└── index.md
```

经我测试，在 index.md 中写 `![](image.png)`，图片正确显示了。

https://gohugo.io/content-management/page-bundles/

---

无非两种组织方式：

一、按文件类型组织，文章为一个文件，图片单独一个文件夹，文章单独一个文件夹
二、按文章单独组织，文章为一个文件夹，图片放在该文件夹，文章也放在该文件夹

以二的类，一的方式是割裂的，文图与文章不在一个目录；但以一的类，二的方式也是割裂的，`.md` 不在一个目录，`.png` 不在一个目录。

---

最后，主题对你说的这种方式，由于图片是相对路径，处理起来比较麻烦，所以有些功能是不支持的，比如图片的外链等图片相关的功能。

**Comment by driftingdream** [comment]
@reuixiy 谢谢指教！
