### ISSUE TITLE
「将博客部署到星际文件系统（IPFS）」一文中的小错误

### ISSUE THREAD

**Issue by hugojing** [reuixiy/io-oi.me#85]
文章结尾「并通过 http://127.0.0.1:8080/ipns/io-oi.me/ 来访问我的博客哦😝！」中，应该是通过 https://ipfs.io/ipns/io-oi.me/ 来访问。

文章写得很详尽很棒，谢谢你的分享。

**Comment by hugojing** [comment]
噢，你是说先 `ipfs daemon` 启动 Gateway server，再访问 http://127.0.0.1:8080/ipns/io-oi.me/ 吗？理论上应该可以，但我本地加载不出来，是因为性能差吗？

**Comment by reuixiy** [comment]
是的。

网络问题大概。

**Comment by Magic-King** [comment]
想问下，您的ipfs上的博客还有维护嘛？
我现在访问提示的是`ipfs resolve -r /ipns/io-oi.me/: could not resolve name`

**Comment by reuixiy** [comment]
不好意思，没有维护了
