### ISSUE TITLE
图片失效

### ISSUE THREAD

**Issue by Gaotianhe** [reuixiy/io-oi.me#89]
文章链接：https://io-oi.me/tech/hugo-vs-hexo/

**Comment by reuixiy** [comment]
谢谢反馈，今天把博客回到了 GitHub Pages，没把 CNAME 加上，所以挂了，目前已修复。

https://github.com/reuixiy/io-oi.me/issues/87#issuecomment-671068370

**Comment by reuixiy** [comment]
……由于 Service Worker 的缘故，可能再刷新一次
